
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class QuanLyVeTau extends javax.swing.JFrame {
    DanhSachKhachHang ds;//không có không được
    DefaultTableModel model;//hiện thị jtable
    /**
     * Creates new form QuanLyVeTau
     */
    public QuanLyVeTau() {
        initComponents();
        myInit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSoCMND = new javax.swing.JTextField();
        txtTenKH = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNgayDi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtGaDen = new javax.swing.JTextField();
        txtGiaVe = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btThemMoi = new javax.swing.JButton();
        btInToanBoDanhSach = new javax.swing.JButton();
        btXoaCMND = new javax.swing.JButton();
        btTimKiemTheoCMND = new javax.swing.JButton();
        btCapNhat = new javax.swing.JButton();
        btInGaDenHCM = new javax.swing.JButton();
        btThoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("CHƯƠNG TRÌNH QUẢN LÝ VÉ TÀU");

        jLabel2.setText("Số CMND");

        jLabel3.setText("Tên KH");

        txtSoCMND.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSoCMNDKeyPressed(evt);
            }
        });

        txtTenKH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTenKHKeyPressed(evt);
            }
        });

        jLabel4.setText("Ngày đi");

        txtNgayDi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNgayDiKeyPressed(evt);
            }
        });

        jLabel5.setText("Ga đến");

        jLabel6.setText("Giá vé ");

        txtGaDen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtGaDenKeyPressed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Số CMND", "Tên Khách Hàng", "Ngày Đi", "Ga Đến", "Giá vé "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btThemMoi.setText("Thêm mới");
        btThemMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemMoiActionPerformed(evt);
            }
        });

        btInToanBoDanhSach.setText("In toàn bộ danh sách");
        btInToanBoDanhSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInToanBoDanhSachActionPerformed(evt);
            }
        });

        btXoaCMND.setText("Xóa theo CMND");
        btXoaCMND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaCMNDActionPerformed(evt);
            }
        });

        btTimKiemTheoCMND.setText("Tìm kiếm theo CMND");
        btTimKiemTheoCMND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTimKiemTheoCMNDActionPerformed(evt);
            }
        });

        btCapNhat.setText("Cập nhật");
        btCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCapNhatActionPerformed(evt);
            }
        });

        btInGaDenHCM.setText("In ga đến HCM");
        btInGaDenHCM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInGaDenHCMActionPerformed(evt);
            }
        });

        btThoat.setText("Thoát");
        btThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtSoCMND)
                                .addComponent(txtNgayDi, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                            .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtGaDen)
                    .addComponent(txtGiaVe, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btThemMoi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btInToanBoDanhSach)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btXoaCMND)
                .addGap(18, 18, 18)
                .addComponent(btTimKiemTheoCMND)
                .addGap(18, 18, 18)
                .addComponent(btCapNhat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btInGaDenHCM)
                .addGap(18, 18, 18)
                .addComponent(btThoat)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSoCMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtGaDen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtGiaVe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNgayDi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btThemMoi)
                    .addComponent(btInToanBoDanhSach)
                    .addComponent(btXoaCMND)
                    .addComponent(btTimKiemTheoCMND)
                    .addComponent(btCapNhat)
                    .addComponent(btInGaDenHCM)
                    .addComponent(btThoat))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSoCMNDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoCMNDKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            txtTenKH.requestFocus();//Tạo phím enter
        }
    }//GEN-LAST:event_txtSoCMNDKeyPressed

    private void txtTenKHKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenKHKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            txtNgayDi.requestFocus();
        }
    }//GEN-LAST:event_txtTenKHKeyPressed

    private void txtNgayDiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNgayDiKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            txtGaDen.requestFocus();
        }
    }//GEN-LAST:event_txtNgayDiKeyPressed

    private void txtGaDenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGaDenKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            txtGiaVe.requestFocus();
        }
    }//GEN-LAST:event_txtGaDenKeyPressed

    private void btThemMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemMoiActionPerformed
        // TODO add your handling code here:
        
        KhachHang kh = new KhachHang(txtSoCMND.getText(),
                txtTenKH.getText(),txtGaDen.getText(),chuyenChuoiThanhNgay(txtNgayDi.getText()),Double.parseDouble(txtGiaVe.getText()));
                ds.ThemVaoDanhSach(kh);//Nhập vào database
                napDuLieuChoTable();
                setBlank();
    }//GEN-LAST:event_btThemMoiActionPerformed

    private void btInToanBoDanhSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInToanBoDanhSachActionPerformed
        // TODO add your handling code here:
        xoaDuLieuTrongTable();
        int stt=0;
        for (KhachHang kh : ds.layDanhSachKhachHang()) {
            themMotDongVaoTable(++stt, kh);
        }
    }//GEN-LAST:event_btInToanBoDanhSachActionPerformed

    private void btXoaCMNDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaCMNDActionPerformed
        // TODO add your handling code here:
        if (ds.xoaTheoCMND(txtSoCMND.getText())) {
            napDuLieuChoTable();
        } else {
            JOptionPane.showMessageDialog(this,"không có");
        }
    }//GEN-LAST:event_btXoaCMNDActionPerformed

    private void btTimKiemTheoCMNDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTimKiemTheoCMNDActionPerformed
        // TODO add your handling code here:
        KhachHang kh = ds.timKiemTheoCMND(txtSoCMND.getText());
        if (kh==null) {
            JOptionPane.showMessageDialog(this,"khong co");
        } else {
            int stt=0;
            xoaDuLieuTrongTable();
            themMotDongVaoTable(++stt, kh);
        }
    }//GEN-LAST:event_btTimKiemTheoCMNDActionPerformed

    private void btInGaDenHCMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInGaDenHCMActionPerformed
        // TODO add your handling code here:
        int stt=0;
        for (KhachHang kh : ds.layDanhSachTPHCM(txtGaDen.getText())) {
            themMotDongVaoTable(++stt, kh);
        }
    }//GEN-LAST:event_btInGaDenHCMActionPerformed

    private void btThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThoatActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(this,"Bạn có chắc chắn thoát không ? ","Thông báo",2)==0){
            this.dispose();
        }
    }//GEN-LAST:event_btThoatActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int index = jTable1.getSelectedRow();
        if (evt.getClickCount()==2) {
            txtSoCMND.setText(jTable1.getValueAt(index,1).toString());
            txtTenKH.setText(jTable1.getValueAt(index, 2).toString());
            txtNgayDi.setText(jTable1.getValueAt(index,3).toString());
            txtGaDen.setText(jTable1.getValueAt(index, 4).toString());
            txtGiaVe.setText(jTable1.getValueAt(index, 5).toString());
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCapNhatActionPerformed
        // TODO add your handling code here:
        int index = jTable1.getSelectedRow();//chọn 1 dong trong jtablel
        if (index==-1) {//nếu không cọn mà bấm bt cập nhật
            JOptionPane.showMessageDialog(this,"chua chon ban ghi");
        } else {//nếu có chọn
            //truy cập tới bản ghi trong ArrayList
            KhachHang kh = ds.danhsachs.get(index);
            kh.setSoCMND(txtSoCMND.getText());
            kh.setTenKH(txtTenKH.getText());
            kh.setNgayDi(chuyenChuoiThanhNgay(txtNgayDi.getText()));
            kh.setGaDen(txtGaDen.getText());
            kh.setGiaVe(Double.parseDouble(txtGiaVe.getText()));
            napDuLieuChoTable();
            setBlank();
        }
    }//GEN-LAST:event_btCapNhatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyVeTau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyVeTau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyVeTau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyVeTau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyVeTau().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCapNhat;
    private javax.swing.JButton btInGaDenHCM;
    private javax.swing.JButton btInToanBoDanhSach;
    private javax.swing.JButton btThemMoi;
    private javax.swing.JButton btThoat;
    private javax.swing.JButton btTimKiemTheoCMND;
    private javax.swing.JButton btXoaCMND;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtGaDen;
    private javax.swing.JTextField txtGiaVe;
    private javax.swing.JTextField txtNgayDi;
    private javax.swing.JTextField txtSoCMND;
    private javax.swing.JTextField txtTenKH;
    // End of variables declaration//GEN-END:variables

    private void myInit() {
        setTitle("Chương trình Quản lý vé tàu ");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        model=(DefaultTableModel) jTable1.getModel();
        jTable1.setModel(model);
        ds = new DanhSachKhachHang();
    }

    private Date chuyenChuoiThanhNgay(String text) {
        try {
            return  new SimpleDateFormat("dd/MM/yyyy").parse(text);
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        return null;
    }
    public  void themMotDongVaoTable(int stt, KhachHang kh){
        model.addRow(new Object[]{stt,kh.getSoCMND(),kh.getTenKH(),chuyenNgayThanhChuoi(kh.getNgayDi()),kh.getGaDen(),kh.getGiaVe()});
    }
    public void xoaDuLieuTrongTable(){
        for (int i = jTable1.getRowCount(); i >0; i--) {
            model.removeRow(i-1);
        }
    }
    public void napDuLieuChoTable(){
        int stt=0;
        xoaDuLieuTrongTable();
        for (KhachHang kh : ds.layDanhSachKhachHang()) {
            themMotDongVaoTable(++stt, kh);
        }
    }
    public void setBlank(){
        txtSoCMND.setText("");
        txtTenKH.setText("");
        txtNgayDi.setText("");
        txtGaDen.setText("");txtGiaVe.setText("");
        txtSoCMND.requestFocus();
    }
    public String chuyenNgayThanhChuoi(Date ngay){
        return  new SimpleDateFormat("dd/MM/yyyy").format(ngay);
    }
}
