
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author TinyThao
 */
public class GUI extends javax.swing.JFrame {

    DanhSachSach ds;
    DefaultTableModel model;

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        myInit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_maSach = new javax.swing.JTextField();
        txt_ngayNhap = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_donGia = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_soLuong = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_tinhTrang = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_thue = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cb_loaiSach = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        b_themMoi = new javax.swing.JButton();
        b_thanhTien = new javax.swing.JButton();
        b_hienThi = new javax.swing.JButton();
        b_xoaTheoMa = new javax.swing.JButton();
        b_timTheoMa = new javax.swing.JButton();
        b_tinhTrang = new javax.swing.JButton();
        B_capnhat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ma Sach");

        jLabel2.setText("Ngay Nhap");

        jLabel3.setText("Don Gia");

        jLabel4.setText("So Luong");

        jLabel5.setText("Tinh Trang");

        jLabel6.setText("Thue");

        jLabel7.setText("Loai Sach");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Ma Sach", "Ngay Nhap", "Don Gia", "So Luong", "Tinh Trang", "Thue"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        b_themMoi.setText("Them Moi");
        b_themMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_themMoiActionPerformed(evt);
            }
        });

        b_thanhTien.setText("Thanh Tien Theo Loai");
        b_thanhTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_thanhTienActionPerformed(evt);
            }
        });

        b_hienThi.setText("Hien Thi");
        b_hienThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_hienThiActionPerformed(evt);
            }
        });

        b_xoaTheoMa.setText("Xoa theo ma");
        b_xoaTheoMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_xoaTheoMaActionPerformed(evt);
            }
        });

        b_timTheoMa.setText("Tim Theo Ma");
        b_timTheoMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_timTheoMaActionPerformed(evt);
            }
        });

        b_tinhTrang.setText("in Tinh Trang");
        b_tinhTrang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_tinhTrangActionPerformed(evt);
            }
        });

        B_capnhat.setText("Cap Nhat");
        B_capnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_capnhatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_donGia, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_soLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(89, 89, 89)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_thue, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cb_loaiSach, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txt_tinhTrang, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(B_capnhat, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_maSach, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_ngayNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b_themMoi)
                                .addGap(14, 14, 14)
                                .addComponent(b_hienThi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b_timTheoMa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b_xoaTheoMa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b_thanhTien)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b_tinhTrang)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_maSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ngayNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_donGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_soLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_loaiSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_tinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_thue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B_capnhat))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_themMoi)
                    .addComponent(b_timTheoMa)
                    .addComponent(b_xoaTheoMa)
                    .addComponent(b_hienThi)
                    .addComponent(b_thanhTien)
                    .addComponent(b_tinhTrang))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_hienThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_hienThiActionPerformed
        // TODO add your handling code here:
        int stt = 0;
        xoaDuLieuTrongJtable();
        for (Sach s : ds.layToanBoDanhSach()) {
            stt++;
            themMotDanhVaoDanhSach(stt, s);
        }
    }//GEN-LAST:event_b_hienThiActionPerformed

    private void b_themMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_themMoiActionPerformed
        // TODO add your handling code here:
        if (cb_loaiSach.getSelectedIndex() == 0) {
            SachGiaoKhoa gk = new SachGiaoKhoa(txt_tinhTrang.getText(),
                                          txt_maSach.getText(),
                                          chuyenChuoiThanhNgay(txt_ngayNhap.getText()),
                                          Integer.parseInt(txt_donGia.getText()),
                                          Integer.parseInt(txt_soLuong.getText()));
            ds.themVaoDanhSach(gk);
        } else {
            //double thue, String maSach, Date ngayNhap, int donGia, int soLuong
            SachThamKhoa tk = new SachThamKhoa(Double.parseDouble(txt_thue.getText()),
                                          txt_maSach.getText(),
                                          chuyenChuoiThanhNgay(txt_ngayNhap.getText()),
                                          Integer.parseInt(txt_donGia.getText()),
                                          Integer.parseInt(txt_soLuong.getText()));
            ds.themVaoDanhSach(tk);
        }
        setBlank();
        napDuLieuVaoJtable();
    }//GEN-LAST:event_b_themMoiActionPerformed

    private void b_timTheoMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_timTheoMaActionPerformed
        // TODO add your handling code here:
        Sach s = ds.timSachTheoMaChiDinh(txt_maSach.getText());
        xoaDuLieuTrongJtable();
        if (s != null) {
            themMotDanhVaoDanhSach(1, s);
        } else {
            JOptionPane.showMessageDialog(this, "Khong co ma sach nay!");
        }
    }//GEN-LAST:event_b_timTheoMaActionPerformed

    private void b_xoaTheoMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_xoaTheoMaActionPerformed
        // TODO add your handling code here:
        boolean s = ds.xoaSachTheoMa(txt_maSach.getText());
        if (s) {
            JOptionPane.showMessageDialog(this, "xoa thanh cong");
        } else {
            JOptionPane.showMessageDialog(this, "xoa that bai");
        }

        // in ra lai danh sach sau khi xoa
        int stt = 0;
        xoaDuLieuTrongJtable();
        for (Sach a : ds.layToanBoDanhSach()) {
            stt++;
            themMotDanhVaoDanhSach(stt, a);
        }
    }//GEN-LAST:event_b_xoaTheoMaActionPerformed

    private void b_thanhTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_thanhTienActionPerformed
        // TODO add your handling code here:
        /*
        if (cb_loaiSach.getSelectedIndex() == 0) {
            double tong = ds.tinhTongThanhTienTheoTungLoai("giao khoa");
            JOptionPane.showMessageDialog(this, "Tong tien Sach Giao Khoa la: " + tong);
        } else {
            double tong = ds.tinhTongThanhTienTheoTungLoai("tham khao");
            JOptionPane.showMessageDialog(this, "Tong tien Sach tham khao la: " + tong);
        }
        */
        double tong = ds.tinhTongThanhTienTheoTungLoai(cb_loaiSach.getSelectedItem().toString());
        JOptionPane.showMessageDialog(this, "Tong tien Sach Giao Khoa la: " + tong);
        
    }//GEN-LAST:event_b_thanhTienActionPerformed

    private void b_tinhTrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_tinhTrangActionPerformed
        // TODO add your handling code here:
        layDanhSachTheoTinhTrang();
    }//GEN-LAST:event_b_tinhTrangActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        //"STT", "Ma Sach", "Ngay Nhap", "Don Gia", "So Luong", "Tinh Trang", "Thue"
        int chon = jTable1.getSelectedRow();
        if (evt.getClickCount() == 2) {
            txt_maSach.setText(jTable1.getValueAt(chon, 1).toString());
            //txt_ngayNhap.setText(jTable1.getValueAt(chon, 2).toString());
            txt_donGia.setText(jTable1.getValueAt(chon, 3).toString());
            txt_soLuong.setText(jTable1.getValueAt(chon, 4).toString());
            txt_tinhTrang.setText(jTable1.getValueAt(chon, 5).toString());
            txt_thue.setText(jTable1.getValueAt(chon, 6).toString());
            try {
                txt_ngayNhap.setText(jTable1.getValueAt(chon, 2).toString());
            } catch (Exception e) {
                txt_ngayNhap.setText("");
                //JOptionPane.showMessageDialog(this, "Nhap ngay sai");
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void B_capnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_capnhatActionPerformed
        // TODO add your handling code here:
        int index = jTable1.getSelectedRow();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Ban chua chon dong!!!");
        } else {
            Sach s = ds.danhSachs.get(index);
            if (s instanceof SachGiaoKhoa) {
                SachGiaoKhoa gk = (SachGiaoKhoa) s;
                //gk = (SachGiaoKhoa) ds.danhSachs.get(index);
                gk.setMaSach(txt_maSach.getText());
                gk.setNgayNhap(chuyenChuoiThanhNgay(txt_ngayNhap.getText()));
                gk.setSoLuong(Integer.parseInt(txt_soLuong.getText()));
                gk.setDonGia(Integer.parseInt(txt_donGia.getText()));
                gk.setTinhTrang(txt_tinhTrang.getText());
            } else {
                SachThamKhoa tk = (SachThamKhoa) s;
                //tk = (SachThamKhoa) ds.danhSachs.get(index);
                tk.setMaSach(txt_maSach.getText());
                tk.setNgayNhap(chuyenChuoiThanhNgay(txt_ngayNhap.getText()));
                tk.setSoLuong(Integer.parseInt(txt_soLuong.getText()));
                tk.setDonGia(Integer.parseInt(txt_donGia.getText()));
                tk.setThue(Double.parseDouble(txt_thue.getText()));
            }
            setBlank();
            napDuLieuVaoJtable();
        }
    }//GEN-LAST:event_B_capnhatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_capnhat;
    private javax.swing.JButton b_hienThi;
    private javax.swing.JButton b_thanhTien;
    private javax.swing.JButton b_themMoi;
    private javax.swing.JButton b_timTheoMa;
    private javax.swing.JButton b_tinhTrang;
    private javax.swing.JButton b_xoaTheoMa;
    private javax.swing.JComboBox<String> cb_loaiSach;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_donGia;
    private javax.swing.JTextField txt_maSach;
    private javax.swing.JTextField txt_ngayNhap;
    private javax.swing.JTextField txt_soLuong;
    private javax.swing.JTextField txt_thue;
    private javax.swing.JTextField txt_tinhTrang;
    // End of variables declaration//GEN-END:variables

    private void myInit() {
        setLocationRelativeTo(null);
        setTitle("quan ly sach");

        ds = new DanhSachSach();
        model = (DefaultTableModel) jTable1.getModel();
        jTable1.setModel(this.model);
        cb_loaiSach.addItem("Sach Giao Khoa");
        cb_loaiSach.addItem("Sach Tham Khao");
    }

    private void setBlank() {
        txt_donGia.setText("");
        txt_maSach.setText("");
        txt_ngayNhap.setText("");
        txt_soLuong.setText("");
        txt_thue.setText("");
        txt_tinhTrang.setText("");
        txt_maSach.requestFocus();
    }

    private Date chuyenChuoiThanhNgay(String s) {
        try {
            return new SimpleDateFormat("dd/MM/yyyy").parse(s);
        } catch (Exception e) {
        }
        return null;
    }

    private String chuyenNgayThanhChuoi(Date d) {
        try {
            return new SimpleDateFormat("dd/MM/yyyy").format(d);
        } catch (Exception e) {
        }
        return null;
    }

    public void xoaDuLieuTrongJtable() {
        for (int i = jTable1.getRowCount(); i > 0; i--) {
            model.removeRow(i - 1);
        }
    }

    public void napDuLieuVaoJtable() {
        int stt = 0;
        xoaDuLieuTrongJtable();
        for (Sach s : ds.layToanBoDanhSach()) {
            themMotDanhVaoDanhSach(++stt, s);
        }
    }

    public void layDanhSachTheoTinhTrang() {
        int stt = 0;
        xoaDuLieuTrongJtable();
        for (Sach s : ds.inSachTheoTinhTrang(txt_tinhTrang.getText())) {
            themMotDanhVaoDanhSach(++stt, s);
        }
    }

    public void themMotDanhVaoDanhSach(int stt, Sach s) {
        if (s instanceof SachGiaoKhoa) {
            SachGiaoKhoa gk = (SachGiaoKhoa) s;
            model.addRow(new Object[]{stt, gk.getMaSach(), chuyenNgayThanhChuoi(gk.getNgayNhap()), gk.getDonGia(),
                gk.getSoLuong(), gk.getTinhTrang(), ""});
        } else {
            SachThamKhoa tk = (SachThamKhoa) s;
            model.addRow(new Object[]{stt, tk.getMaSach(), chuyenNgayThanhChuoi(tk.getNgayNhap()), tk.getDonGia(),
                tk.getSoLuong(), "", tk.getThue()});
        }
    }//"STT", "Ma Sach", "Ngay Nhap", "Don Gia", "So Luong", "Tinh Trang", "Thue"

}
