/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import core.Bus;
import core.Car;
import core.CarList;
import core.LuxuryCar;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thanh
 */
public class CarManager extends javax.swing.JFrame {
    CarList ds;
    DefaultTableModel model;
    /**
     * Creates new form CarManager
     */
    public CarManager() {
        initComponents();
        myInit();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbCar = new javax.swing.JComboBox<>();
        txtBienSo = new javax.swing.JTextField();
        txtNhaSX = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSoCN = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNamSX = new javax.swing.JTextField();
        txtGiaGoc = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btThem = new javax.swing.JButton();
        btXoa = new javax.swing.JButton();
        btTimKiem = new javax.swing.JButton();
        btCapNhap = new javax.swing.JButton();
        btGiaXeNN = new javax.swing.JButton();
        btThoat = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtTuyenDuong = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCuocVC = new javax.swing.JTextField();
        txtLPTTDB = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtThue = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("CHƯƠNG TRÌNH QUẢN LÝ CAR MANAGER");

        jLabel2.setText("Biển Số:");

        jLabel3.setText("Nhà SX:");

        cbCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCarActionPerformed(evt);
            }
        });

        txtNhaSX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNhaSXActionPerformed(evt);
            }
        });

        jLabel4.setText("Số chỗ ngồi:");

        jLabel5.setText("Năm SX:");

        jLabel6.setText("Giá gốc:");

        txtGiaGoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaGocActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Biển Số:", "Nhà SX:", "Số chỗ ngồi:", "Năm SX:", "tuyến Đ:", "Giá G:", "Cước VC:", "lệ PhiTTDB:", "Thuế:", "Giá xe:"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btThem.setText("Thêm");
        btThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemActionPerformed(evt);
            }
        });

        btXoa.setText("Xóa");
        btXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });

        btTimKiem.setText("Tìm Kiếm");
        btTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTimKiemActionPerformed(evt);
            }
        });

        btCapNhap.setText("Cập nhập");
        btCapNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btCapNhapMouseClicked(evt);
            }
        });
        btCapNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCapNhapActionPerformed(evt);
            }
        });

        btGiaXeNN.setText("Giá xe NN");
        btGiaXeNN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGiaXeNNActionPerformed(evt);
            }
        });

        btThoat.setText("Thoát");
        btThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThoatActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Bus"));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel7.setText("Tuyến Đường:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTuyenDuong, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTuyenDuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("LuxuryCar"));

        jLabel8.setText("Cước vận chuyển:");

        jLabel9.setText("Lệ phí TTDB:");

        jLabel10.setText("thuế: ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCuocVC)
                    .addComponent(txtThue, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addComponent(txtLPTTDB)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtCuocVC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtLPTTDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(txtThue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtBienSo)
                            .addComponent(txtNhaSX)
                            .addComponent(txtSoCN, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtGiaGoc, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                                    .addComponent(txtNamSX))
                                .addGap(82, 82, 82)
                                .addComponent(cbCar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btThem)
                                .addGap(31, 31, 31)
                                .addComponent(btXoa)
                                .addGap(27, 27, 27)
                                .addComponent(btTimKiem)
                                .addGap(26, 26, 26)
                                .addComponent(btCapNhap)
                                .addGap(27, 27, 27)
                                .addComponent(btGiaXeNN)
                                .addGap(34, 34, 34)
                                .addComponent(btThoat))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(52, 52, 52))
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtBienSo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtNamSX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNhaSX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtGiaGoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtSoCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btThem)
                    .addComponent(btXoa)
                    .addComponent(btTimKiem)
                    .addComponent(btCapNhap)
                    .addComponent(btGiaXeNN)
                    .addComponent(btThoat))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNhaSXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNhaSXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNhaSXActionPerformed

    private void txtGiaGocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaGocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaGocActionPerformed

    private void btThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemActionPerformed
        if (cbCar.getSelectedIndex()==0) {
            Bus b = new Bus(txtTuyenDuong.getText(),txtBienSo.getText(),txtNhaSX.getText(),Integer.parseInt(txtSoCN.getText()), 
                    chuyenNgayThanhChuoi(txtNamSX.getText()),Double.parseDouble(txtGiaGoc.getText()));
            ds.themVaoDanhSachCar(b);
        }else{
            LuxuryCar lc = new LuxuryCar(Double.parseDouble(txtCuocVC.getText()),
                    Double.parseDouble(txtLPTTDB.getText()),Double.parseDouble(txtThue.getText()),txtBienSo.getText(),
                    txtNhaSX.getText(), 
                    Integer.parseInt(txtSoCN.getText()), 
                    chuyenNgayThanhChuoi(txtNamSX.getText()),Double.parseDouble(txtGiaGoc.getText()));
            ds.themVaoDanhSachCar(lc);
        }
        napDuLieuVaoTable();
    }//GEN-LAST:event_btThemActionPerformed

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed
        // TODO add your handling code here:
        if (ds.xoaTheoBienSo(txtBienSo.getText())) {
            napDuLieuVaoTable();
        }else{
            JOptionPane.showMessageDialog(this,"không có");
        }
    }//GEN-LAST:event_btXoaActionPerformed

    private void cbCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCarActionPerformed
        // TODO add your handling code here:
        if (cbCar.getSelectedIndex()==0) {
            jPanel1.setVisible(true);
            jPanel2.setVisible(false);
        }else{
            jPanel1.setVisible(false);
            jPanel2.setVisible(true);
        }
    }//GEN-LAST:event_cbCarActionPerformed

    private void btTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTimKiemActionPerformed
        // TODO add your handling code here:
        Car c = ds.timTheoBienSo(txtBienSo.getText());
        if (c==null) {
            JOptionPane.showMessageDialog(this,"không tìm thấy");
        }else{
            xoaDuLieuTrongTable();
            themMotDongVaoTable(c);
        }
    }//GEN-LAST:event_btTimKiemActionPerformed

    private void btThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btThoatActionPerformed

    private void btGiaXeNNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGiaXeNNActionPerformed
        // TODO add your handling code here:
        xoaDuLieuTrongTable();
        for (Car c : ds.layDanhSachGiaXeNhoNhat()) {
            themMotDongVaoTable(c);
        }
    }//GEN-LAST:event_btGiaXeNNActionPerformed

    private void btCapNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCapNhapActionPerformed
        // TODO add your handling code here:
        int index=jTable1.getSelectedRow();
        if (index==-1) {
            JOptionPane.showMessageDialog(this, "Chua chon");
        } else {
            Car car=ds.layDanhSachCar().get(index);
            if (car instanceof Bus) {
                Bus bus=(Bus) car;
                bus.setBienSo(txtBienSo.getText());
                bus.setGiaGoc(Double.parseDouble(txtGiaGoc.getText()));
                bus.setNamSX(chuyenNgayThanhChuoi(txtNamSX.getText()));
                bus.setNhaSX(txtNhaSX.getText());
                bus.setSoChoNgoi(Integer.parseInt(txtSoCN.getText()));
                bus.setTuyenDuong(txtTuyenDuong.getText());
            }else{
                LuxuryCar lc =(LuxuryCar) car;
                lc.setBienSo(txtBienSo.getText());
                lc.setGiaGoc(Double.parseDouble(txtGiaGoc.getText()));
                lc.setNamSX(chuyenNgayThanhChuoi(txtNamSX.getText()));
                lc.setNhaSX(txtNhaSX.getText());
                lc.setSoChoNgoi(Integer.parseInt(txtSoCN.getText()));
                lc.setCuocVanChuyen(Double.parseDouble(txtCuocVC.getText()));
                lc.setLePhiTTDB(Double.parseDouble(txtLPTTDB.getText()));
                lc.setThue(Double.parseDouble(txtThue.getText()));
            
            }
        }
        napDuLieuVaoTable();
    }//GEN-LAST:event_btCapNhapActionPerformed

    private void btCapNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCapNhapMouseClicked
        // TODO add your handling code here:
          int index = jTable1.getSelectedRow();
        if (evt.getClickCount()==2) {
            txtBienSo.setText(jTable1.getValueAt(index,0).toString());
            txtNhaSX.setText(jTable1.getValueAt(index, 1).toString());
            txtSoCN.setText(jTable1.getValueAt(index,2).toString());
            txtNamSX.setText(jTable1.getValueAt(index, 3).toString());
            txtGiaGoc.setText(jTable1.getValueAt(index, 4).toString());
            txtTuyenDuong.setText(jTable1.getValueAt(index,5).toString());
            txtCuocVC.setText(jTable1.getValueAt(index, 6).toString());
            txtLPTTDB.setText(jTable1.getValueAt(index,7).toString());
            txtThue.setText(jTable1.getValueAt(index, 8).toString());
//            .setText(jTable1.getValueAt(index, 9).toS
        
            
        }
    }//GEN-LAST:event_btCapNhapMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCapNhap;
    private javax.swing.JButton btGiaXeNN;
    private javax.swing.JButton btThem;
    private javax.swing.JButton btThoat;
    private javax.swing.JButton btTimKiem;
    private javax.swing.JButton btXoa;
    private javax.swing.JComboBox<String> cbCar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtBienSo;
    private javax.swing.JTextField txtCuocVC;
    private javax.swing.JTextField txtGiaGoc;
    private javax.swing.JTextField txtLPTTDB;
    private javax.swing.JTextField txtNamSX;
    private javax.swing.JTextField txtNhaSX;
    private javax.swing.JTextField txtSoCN;
    private javax.swing.JTextField txtThue;
    private javax.swing.JTextField txtTuyenDuong;
    // End of variables declaration//GEN-END:variables

    private void myInit() {
        setTitle("Car Manager");
        setLocationRelativeTo(null);
        model = (DefaultTableModel) jTable1.getModel();
        ds = new CarList();
        cbCar.addItem("Bus");
        cbCar.addItem("Luxury Car");
    }
    public Date chuyenNgayThanhChuoi(String str){
        try {
            return new SimpleDateFormat("dd/MM/yyyy").parse(str);
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        return null;
    }
    public String chuyenChuoiThanhNgay(Date date){
        return new SimpleDateFormat("dd/MM/yyyy").format(date);
    }
    public void themMotDongVaoTable(Car c){
        if (c instanceof Bus) {
            Bus  b = (Bus) c;
            model.addRow(new Object[]{b.getBienSo(),b.getNhaSX(),b.getSoChoNgoi(),
                chuyenChuoiThanhNgay(b.getNamSX()),b.getTuyenDuong(),b.getGiaGoc(),0,0,0,b.tinhGiaXe()});
        }else{
            LuxuryCar lc = (LuxuryCar)c;
            model.addRow(new Object[]{lc.getBienSo(),lc.getNhaSX(),lc.getSoChoNgoi(),chuyenChuoiThanhNgay(lc.getNamSX())
            ,lc.getGiaGoc(),0,lc.getCuocVanChuyen(),lc.getLePhiTTDB(),lc.getThue(),lc.tinhGiaXe()});
        }
    }
    public void xoaDuLieuTrongTable(){
        for (int i = jTable1.getRowCount(); i>0; i--) {
             model.removeRow(i-1);
        }
    }
    public void napDuLieuVaoTable(){
        xoaDuLieuTrongTable();
        for (Car c : ds.layDanhSachCar()) {
            themMotDongVaoTable(c);
        }
    }
}
