/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import com.sun.org.apache.xpath.internal.compiler.OpMap;
import core.DanhSachNhanVien;
import core.NhanVien;
import core.NhanVienBanHang;
import core.NhanVienQuanLy;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thanh
 */
public class QuanLyNhanVien extends javax.swing.JFrame {
    DanhSachNhanVien ds;
    DefaultTableModel model;
    /**
     * Creates new form QuanLyNhanVien
     */
    public QuanLyNhanVien() {
        initComponents();
        myInit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        txtTenNV = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cbNhanVien = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNgayVL = new javax.swing.JTextField();
        txtHeSL = new javax.swing.JTextField();
        btThem = new javax.swing.JButton();
        btXoa = new javax.swing.JButton();
        btHienThiDanhSach = new javax.swing.JButton();
        btMaNV = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtChucVu = new javax.swing.JTextField();
        txtPC = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtSPBan = new javax.swing.JTextField();
        btThoat = new javax.swing.JButton();
        btNVBHNN = new javax.swing.JButton();
        btCapNhap = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Quản Lý Nhân Viên ");

        jLabel2.setText("Mã NV:");

        jLabel3.setText("Tên NV:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã NV:", "Tên NV:", "Ngày Vào Làm:", "Hệ Số Lương:", "Chức Vụ:", "PC Chức Vụ:", "Số SP bán: ", "Lương"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        cbNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNhanVienActionPerformed(evt);
            }
        });

        jLabel4.setText("Ngày Vào Làm:");

        jLabel5.setText("Hệ Số Lương:");

        txtHeSL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHeSLActionPerformed(evt);
            }
        });

        btThem.setText("Thêm ");
        btThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemActionPerformed(evt);
            }
        });

        btXoa.setText("Xoa");
        btXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });

        btHienThiDanhSach.setText("Hiển thị danh sách");
        btHienThiDanhSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHienThiDanhSachActionPerformed(evt);
            }
        });

        btMaNV.setText("Tìm MNV");
        btMaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMaNVActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("NV Quản Lý"));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("Chức vụ:");

        jLabel7.setText("Phụ cấp chức vụ: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPC, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("NV bán Hàng"));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel8.setText("Số sản  phẩm bán : ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtSPBan, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtSPBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        btThoat.setText("Thoát");
        btThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThoatActionPerformed(evt);
            }
        });

        btNVBHNN.setText("Tìm nhân viên bán được hàng NN");
        btNVBHNN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNVBHNNActionPerformed(evt);
            }
        });

        btCapNhap.setText("Cập nhập");
        btCapNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btCapNhapMouseClicked(evt);
            }
        });
        btCapNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCapNhapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(31, 31, 31))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(27, 27, 27)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(207, 207, 207)
                                .addComponent(cbNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNgayVL)
                                    .addComponent(txtHeSL, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                                .addGap(28, 28, 28)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btThem)
                                .addGap(38, 38, 38)
                                .addComponent(btXoa)
                                .addGap(36, 36, 36)
                                .addComponent(btHienThiDanhSach)
                                .addGap(50, 50, 50)
                                .addComponent(btMaNV)
                                .addGap(43, 43, 43)
                                .addComponent(btThoat)
                                .addGap(18, 18, 18)
                                .addComponent(btNVBHNN))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btCapNhap)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(cbNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgayVL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(txtHeSL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btThem)
                    .addComponent(btXoa)
                    .addComponent(btHienThiDanhSach)
                    .addComponent(btMaNV)
                    .addComponent(btThoat)
                    .addComponent(btNVBHNN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btCapNhap)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHeSLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHeSLActionPerformed
        // TODO add your handling code here:
        try {
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtHeSLActionPerformed

    private void cbNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNhanVienActionPerformed
        // TODO add your handling code here:
        if (cbNhanVien.getSelectedIndex()==0) {
            jPanel1.setVisible(true);
            jPanel2.setVisible(false);
        } else {
            jPanel2.setVisible(true);
            jPanel1.setVisible(false);
        }
    }//GEN-LAST:event_cbNhanVienActionPerformed

    private void btThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemActionPerformed
        // TODO add your handling code here:
        if (cbNhanVien.getSelectedIndex()==0) {
            NhanVienQuanLy nvql = new NhanVienQuanLy(txtChucVu.getText(),
                    Double.parseDouble(txtPC.getText()),txtMaNV.getText(),txtTenNV.getText(),
                    chuyenNgayThanhChuoi(txtNgayVL.getText()),
            Double.parseDouble(txtHeSL.getText()));
            ds.themDanhSachNhanVien(nvql);
        }else{
            NhanVienBanHang nvbh = new NhanVienBanHang(Integer.parseInt(txtSPBan.getText()),txtMaNV.getText(),
                    txtTenNV.getText(),chuyenNgayThanhChuoi(txtNgayVL.getText()),
                    Double.parseDouble(txtHeSL.getText()));
            ds.themDanhSachNhanVien(nvbh);
        }
        napDuLieuVaoTable();
    }//GEN-LAST:event_btThemActionPerformed

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed
        // TODO add your handling code here:
        if (ds.xoaNhanVienTheoMa(txtMaNV.getText())) {
            napDuLieuVaoTable();
        } else {
            JOptionPane.showMessageDialog(this,"Không có");
        }
    }//GEN-LAST:event_btXoaActionPerformed

    private void btHienThiDanhSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHienThiDanhSachActionPerformed
        // TODO add your handling code here:
        xoaDuLieuTable();
        for (NhanVien nv : ds.layDanhSachNhanVien()) {
            themMotDongVaoTable(nv);
        }
    }//GEN-LAST:event_btHienThiDanhSachActionPerformed

    private void btMaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMaNVActionPerformed
        // TODO add your handling code here:
        NhanVien nv = ds.timNhanVienTheoMa(txtMaNV.getText());
        if (nv==null) {
            JOptionPane.showMessageDialog(this,"Không tìm thấy");
        } else {
            xoaDuLieuTable();
            themMotDongVaoTable(nv);
        }
         
    }//GEN-LAST:event_btMaNVActionPerformed

    private void btThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btThoatActionPerformed

    private void btNVBHNNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNVBHNNActionPerformed
        // TODO add your handling code here:
       NhanVien nv=ds.timNhanVienBanSoSanPhamNhieuNhat(txtMaNV.getText());
       if(nv==null){
           JOptionPane.showMessageDialog(this,"Không tìm thấy ");
       }else{
           xoaDuLieuTable();
           themMotDongVaoTable(nv);
       }
    }//GEN-LAST:event_btNVBHNNActionPerformed

    private void btCapNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCapNhapMouseClicked
        // TODO add your handling code here:\
        int index = jTable1.getSelectedRow();
        if (evt.getClickCount()==2) {
            txtMaNV.setText(jTable1.getValueAt(index,0).toString());
            txtTenNV.setText(jTable1.getValueAt(index,1).toString());
            txtNgayVL.setText(jTable1.getValueAt(index,2).toString());
            txtHeSL.setText(jTable1.getValueAt(index,3).toString());
            txtChucVu.setText(jTable1.getValueAt(index,4).toString());
            txtPC.setText(jTable1.getValueAt(index,5).toString());
            txtSPBan.setText(jTable1.getValueAt(index,6).toString());
            
        }
    }//GEN-LAST:event_btCapNhapMouseClicked

    private void btCapNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCapNhapActionPerformed
        // TODO add your handling code here:
        int index=jTable1.getSelectedRow();
        if (index==-1) {
            JOptionPane.showMessageDialog(this,"chưa chọn");
        }else{
             NhanVien nv = ds.layDanhSachNhanVien().get(index);
             if (nv instanceof NhanVienQuanLy) {
                NhanVienQuanLy nvql = (NhanVienQuanLy) nv;
                nvql.setMaNV(txtMaNV.getText());
                nvql.setTenNV(txtTenNV.getText());
                nvql.setNgayVaoLam(chuyenNgayThanhChuoi(txtNgayVL.getText()));
                nvql.setHeSoLuong(Double.parseDouble(txtHeSL.getText()));
                nvql.setChucVu(txtChucVu.getText());
                nvql.setPhuCapChucVu(Double.parseDouble(txtPC.getText()));
              
                
            }else{
                 NhanVienBanHang nvbh= (NhanVienBanHang) nv;
                 nvbh.setMaNV(txtMaNV.getText());
                nvbh.setTenNV(txtTenNV.getText());
                nvbh.setNgayVaoLam(chuyenNgayThanhChuoi(txtNgayVL.getText()));
                nvbh.setHeSoLuong(Double.parseDouble(txtHeSL.getText()));
                nvbh.setSoSanPhamBan(Integer.parseInt(txtSPBan.getText()));
            }
             napDuLieuVaoTable();
        }
    }//GEN-LAST:event_btCapNhapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCapNhap;
    private javax.swing.JButton btHienThiDanhSach;
    private javax.swing.JButton btMaNV;
    private javax.swing.JButton btNVBHNN;
    private javax.swing.JButton btThem;
    private javax.swing.JButton btThoat;
    private javax.swing.JButton btXoa;
    private javax.swing.JComboBox<String> cbNhanVien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtChucVu;
    private javax.swing.JTextField txtHeSL;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtNgayVL;
    private javax.swing.JTextField txtPC;
    private javax.swing.JTextField txtSPBan;
    private javax.swing.JTextField txtTenNV;
    // End of variables declaration//GEN-END:variables

    private void myInit() {
        setLocationRelativeTo(null);
        setTitle("Chương trình quản lý nhân viên");
        model =(DefaultTableModel)jTable1.getModel();
        ds = new DanhSachNhanVien();
        cbNhanVien.addItem("Nhân viên quản lý ");
        cbNhanVien.addItem("Nhân viên bán hàng");
        jPanel2.setVisible(false);
    }
    public Date chuyenNgayThanhChuoi(String str){
        try {
            return new SimpleDateFormat("dd/mm/yyyy").parse(str);
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
        return null;
    }
    public String chuyenChuoiThanhNgay(Date date){
        return new SimpleDateFormat("dd/mm/yyyy").format(date);
    
    }
    public void themMotDongVaoTable(NhanVien nv){
        if (nv instanceof NhanVienQuanLy) {
            NhanVienQuanLy nvql =(NhanVienQuanLy) nv;
            model.addRow(new Object[]{nvql.getMaNV(),nvql.getTenNV(),chuyenChuoiThanhNgay(nvql.getNgayVaoLam())
            ,nvql.getHeSoLuong(),nvql.getChucVu(),nvql.getPhuCapChucVu(),0,nvql.tinhLuongThucNhan()});
        }else{
            NhanVienBanHang nvbh =(NhanVienBanHang) nv;
            model.addRow(new Object[]{nvbh.getMaNV(),nvbh.getTenNV(),chuyenChuoiThanhNgay(nvbh.getNgayVaoLam()),
            nvbh.getHeSoLuong(),0,0,nvbh.getSoSanPhamBan(),nvbh.tinhLuongThucNhan()});
        }
    }
    public void xoaDuLieuTable(){
        for (int i =jTable1.getRowCount(); i >0; i--) {
            model.removeRow(i-1);
        }
    }
    public void napDuLieuVaoTable(){
        xoaDuLieuTable();
        for (NhanVien nv : ds.layDanhSachNhanVien()) {
            themMotDongVaoTable(nv);
        }
    }
}
